Repository cryptopay-dev/yaga, pull requests merged in 2018-03, with the labels that each got.

#66 [TS-000] Custom Bind + Errors formatter
  errors/errors.go
  web/bind.go
  web/bind_test.go
  web/web.go
Labels: features

#67 [TS-000] Debug error while bind
  web/bind.go
Labels: features

#68 Update bind.go
  web/bind.go
Labels: bug

#69 [TS-000] Extend cacher
  cacher/interface.go
  cacher/redis/redis.go
Labels: features

#71 [TS-246] Yaga. Поправить "валидацию"
  CHANGELOG.md
  validate/format.go
  validate/format_test.go
Labels: refactoring

#72 [TS-000] Cacher (Redis) tests
  .circleci/config.yml
  cacher/redis/redis_test.go
Labels: tests

#74 [GO-9] Fix validation check errors
  CHANGELOG.md
  validate/format.go
  validate/format_test.go
Labels: bug

#73 [GO-3] Work around simplify
  Gopkg.lock
  Gopkg.toml
  cmd/project_example/app/app.go
  cmd/project_example/app/controllers/controllers.go
  config/config.go
  config/config_test.go
  errors/logic.go
  examples/errors/main.go
  examples/helpers-collection/main.go
  examples/middleware-auth/main.go
  examples/middleware-request/main.go
  examples/pprof/main.go
  examples/report/main.go
  examples/validate/main.go
  examples/web/main.go
  helpers/collection/collection.go
  helpers/collection/form.go
  logger/logger.go
  logger/nop/logger.go
  logger/nop/main.go
  logger/zap/logger.go
  middlewares/auth/main.go
  middlewares/auth/model.go
  middlewares/auth/options.go
  middlewares/auth/sample.sql
  middlewares/auth/user.go
  middlewares/auth/user_test.go
  pprof/pprof.go
  tracer/tracer.go
  validate/format.go
  validate/format_test.go
  web/errors.go
  web/logic.go
  web/recover.go
  web/tracer.go
  web/tracer_test.go
  web/web.go
Labels: docs, features, refactoring

#81 [GO-2] Cli-tool refactoring
  .circleci/config.yml
  Gopkg.lock
  README.md
  cli/cli.go
  cli/commands.go
  cli/interface.go
  cmd/builder.go
  cmd/main.go
  cmd/parse.go
  cmd/yaga/Makefile
  cmd/yaga/VERSION
  cmd/yaga/commands/commands.go
  cmd/yaga/commands/db.go
  cmd/yaga/commands/db_test.go
  cmd/yaga/commands/logger.go
  cmd/yaga/commands/migrate_actions.go
  cmd/yaga/commands/migrate_cleanup.go
  cmd/yaga/commands/migrate_create.go
  cmd/yaga/commands/migrate_down.go
  cmd/yaga/commands/migrate_list.go
  cmd/yaga/commands/migrate_up.go
  cmd/yaga/commands/migrate_version.go
  cmd/yaga/commands/project.go
  cmd/yaga/config.example.yaml
  cmd/yaga/internal/version.go
  cmd/yaga/internal/version_test.go
  cmd/yaga/main.go
  cmd/yaga/project_example/Gopkg.toml
  cmd/yaga/project_example/LICENSE
  cmd/yaga/project_example/README.md
  cmd/yaga/project_example/app/app.go
  cmd/yaga/project_example/app/controllers/controllers.go
  cmd/yaga/project_example/app/controllers/options.go
  cmd/yaga/project_example/app/library/config/config.go
  cmd/yaga/project_example/assets/docs/swagger.yaml
  cmd/yaga/project_example/config.example.yml
  cmd/yaga/project_example/main.go
  cmd/yaga/project_example/migrations/.gitkeep
  cmd/yaga/project_example/misc/vars.go
  examples/cli/main.go
  migrate/cmd/main.go
  migrate/migrate.go
Labels: features, refactoring

#77 [GO-6] Bind params to struct
  CHANGELOG.md
  web/bind.go
  web/bind_test.go
Labels: features, refactoring

#82 [FIX] Hot fix (pointer on pointer)
  cli/cli.go
Labels: bug

#84 [FIX] Allow empty body to post request
  .circleci/config.yml
  web/bind.go
  web/bind_test.go
Labels: features

#85 [VENDOR] Bump new Echo version
  Gopkg.lock
  Gopkg.toml
  web/bind.go
Labels: bug, vendor

#86 [FIX] Echo want write something omitting logger
  CHANGELOG.md
  logger/main.go
  logger/nop/main.go
  logger/zap/logger.go
Labels: bug, changelog

#87 [FIX] Rewrite cli/yaga
  CHANGELOG.md
  cli/cli.go
  cli/commands.go
  cli/interface.go
  cli/options.go
  cmd/yaga/VERSION
  examples/cli/main.go
Labels: bug

#89 [GO-48] delete unused code
  cli/cli.go
  cli/interface.go
  cli/options.go
  examples/cli/main.go
Labels: refactoring

#88 [GO-47] fix tests for race
  .circleci/config.yml
  workers/pool.go
  workers/waitgroup.go
  workers/waitgroup_test.go
  workers/workers_test.go
Labels: tests

#90 [GO-33] service for send emails
  Gopkg.lock
  Gopkg.toml
  README.md
  config/mail.go
  examples/mail/main.go
  mail/event.go
  mail/events.go
  mail/logger.go
  mail/mail.go
  mail/options.go
Labels: features

#92 [GO-000] Slashes for work url with pprof
  pprof/pprof.go
Labels: bug

#94 [GO-84] Update to go-metrics 3.0
  Gopkg.lock
  Gopkg.toml
Labels: features, vendor

#95 [GO-83] fix race tests
  workers/mockcron_test.go
  workers/pool.go
  workers/waitgroup.go
  workers/waitgroup_test.go
  workers/workers.go
  workers/workers_test.go
Labels: bug

#91 [GO-85] binding default values
  web/bind.go
  web/bind_test.go
Labels: enhancement

#97 [GO-41] Refactor config
  Gopkg.lock
  Gopkg.toml
  cacher/redis/redis_test.go
  cli/cli.go
  cli/commands.go
  cli/interface.go
  cli/options.go
  cmd/yaga/VERSION
  cmd/yaga/commands/commands.go
  cmd/yaga/commands/db.go
  cmd/yaga/commands/db_test.go
  cmd/yaga/commands/migrate_actions.go
  cmd/yaga/commands/migrate_cleanup.go
  cmd/yaga/commands/migrate_down.go
  cmd/yaga/commands/migrate_list.go
  cmd/yaga/commands/migrate_up.go
  cmd/yaga/commands/migrate_version.go
  cmd/yaga/project_example/Gopkg.toml
  cmd/yaga/project_example/app/app.go
  cmd/yaga/project_example/app/controllers/controllers.go
  cmd/yaga/project_example/app/controllers/options.go
  cmd/yaga/project_example/app/library/config/config.go
  cmd/yaga/project_example/main.go
  cmd/yaga/project_example/misc/vars.go
  config/config.fixture.yaml
  config/config.go
  config/config_test.go
  config/database.go
  config/mail.go
  config/proxy.go
  config/redis.go
  examples/cli/main.go
  examples/config/main.go
  examples/helpers-collection/main.go
  examples/middleware-auth/main.go
  examples/web/main.go
  helpers/mail/mail.go
  helpers/postgres/postgres.go
  helpers/redis/redis.go
  helpers/testdb/main.go
  pprof/pprof.go
  web/errors.go
  web/web.go
Labels: docs, examples, refactoring, vendor

#96 [GO-76] added gracefull component
  Gopkg.lock
  cmd/yaga/project_example/app/app.go
  examples/web/main.go
  graceful/graceful.go
  web/web.go
Labels: features

#99 [GO-89] wrap errors
  cli/commands.go
  middlewares/auth/model.go
  middlewares/auth/user_test.go
  model/methods.go
Labels: features

#100 [GO-90] custom error
  errors/errors.go
Labels: features

#101 [GO-000] locker fix
  locker/locker.go
Labels: bug

#102 [GO-000] race access to redis-lock.Options.LockTimeout (#101)
  locker/locker.go
Labels: bug

#103 [GO-000] Hide types
  helpers/mail/mail.go
  helpers/postgres/postgres.go
  helpers/redis/redis.go
Labels: features
