Repository cryptopay-dev/yaga, pull requests merged in 2018-02, with the labels that each got.

#49 [TS-000] Fix config.Proxy->Apply
  config/proxy.go
Labels: bug

#50 [TS-000] Collection-render helper
  examples/helpers-collection/main.go
  helpers/collection/collection.go
Labels: features

#51 [DEP] Bump vendor
  Gopkg.lock
Labels: vendor

#52 [TS-198] improvement helpers/collection
  examples/helpers-collection/main.go
  helpers/collection/collection.go
  helpers/collection/form.go
  helpers/collection/form_test.go
Labels: features, refactoring

#53 [TS-197] Yaga. Migration library
  .circleci/config.yml
  Gopkg.lock
  README.md
  cli/commands.go
  cli/migrate.go
  cli/options.go
  helpers/testdb/main.go
  logger/zap/logger.go
  middlewares/auth/main_test.go
  migrate/cmd/main.go
  migrate/fixtures/bad/1518853453_first.down.sql
  migrate/fixtures/bad/1518853453_first.up.sql
  migrate/fixtures/good/1512662684_first.down.sql
  migrate/fixtures/good/1512662684_first.up.sql
  migrate/fixtures/good/1512662685_second.down.sql
  migrate/fixtures/good/1512662685_second.up.sql
  migrate/fixtures/good/some-other-file-for-test-ignore.txt
  migrate/helpers.go
  migrate/helpers_test.go
  migrate/migrate.go
  migrate/migrate_test.go
  migrate/vars.go
Labels: features, refactoring

#54 [TS-198] fix fields for validate
  helpers/collection/collection.go
  helpers/collection/form.go
Labels: bug

#48 [TS-189] wrapper for UUID functions
  helpers/uuid.go
  helpers/uuid_test.go
  middlewares/request/tracer.go
  middlewares/request/tracer_test.go
Labels: refactoring

#55 [FIX] Migrations table
  migrate/vars.go
Labels: bug

#58 [TS-215] cli with optional commands
  cli/cli.go
  cli/commands.go
  cli/interface.go
  cli/options.go
  examples/cli/main.go
Labels: features

#59 [FEATURE] Redis configuration
  config/redis.go
Labels: features

#60 [FEATURE] PostgreSQL configuration
  config/database.go
Labels: features

#56 [TS-217] Yaga cmd tool
  Gopkg.toml
  cli/cli.go
  cli/commands.go
  cli/interface.go
  cli/options.go
  cmd/builder.go
  cmd/config.example.yaml
  cmd/main.go
  cmd/parse.go
  cmd/project_example/Gopkg.toml
  cmd/project_example/LICENSE
  cmd/project_example/README.md
  cmd/project_example/app/app.go
  cmd/project_example/app/controllers/controllers.go
  cmd/project_example/app/controllers/options.go
  cmd/project_example/app/library/config/config.go
  cmd/project_example/assets/docs/swagger.yaml
  cmd/project_example/config.example.yml
  cmd/project_example/main.go
  cmd/project_example/migrations/.gitkeep
  cmd/project_example/misc/vars.go
  examples/cli/main.go
Labels: features

#61 [TS-221] Add pprof with set engine and port
  cmd/project_example/app/controllers/controllers.go
  examples/pprof/main.go
  pprof/pprof.go
Labels: features

#62 [UPD] Redis lock upgrade
  Gopkg.lock
  Gopkg.toml
  examples/locker/main.go
  locker/locker.go
Labels: vendor

#63 Update cli.go
  cli/cli.go
Labels: bug

#64 hotfix
  cli/cli.go
Labels: bug

#65 [UPD] Validator errors
  validate/format.go
  validate/format_test.go
Labels: features
