Repository cryptopay-dev/yaga, pull requests merged in 2018-04, with the labels that each got.

#105 [GO-000] Wrap errors
  CHANGELOG.md
  cli/commands.go
  cmd/yaga/VERSION
Labels: bug

#106 [GO-105] added Context for graceful
  cmd/yaga/project_example/app/app.go
  examples/web/main.go
  graceful/graceful.go
Labels: features

#107 [GO-000] Graceful backports
  Gopkg.lock
  graceful/graceful.go
Labels: backport, vendor

#109 [GO-000] Global logger
  Gopkg.lock
  examples/global-logger/config.yml
  examples/global-logger/main.go
  logger/log/log.go
Labels: examples, features, vendor

#110 [GO-000] Rewrite with global logger
  cli/cli.go
  cli/commands.go
  cli/interface.go
  cli/options.go
  cmd/yaga/commands/commands.go
  cmd/yaga/commands/logger.go
  cmd/yaga/commands/migrate_actions.go
  cmd/yaga/commands/migrate_cleanup.go
  cmd/yaga/commands/migrate_down.go
  cmd/yaga/commands/migrate_list.go
  cmd/yaga/commands/migrate_up.go
  cmd/yaga/commands/migrate_version.go
  cmd/yaga/commands/project.go
  cmd/yaga/main.go
  cmd/yaga/project_example/app/app.go
  cmd/yaga/project_example/app/controllers/controllers.go
  cmd/yaga/project_example/app/controllers/options.go
  examples/errors/main.go
  examples/global-logger/main.go
  examples/helpers-collection/main.go
  examples/locker/main.go
  examples/middleware-auth/main.go
  examples/middleware-request/main.go
  examples/pprof/main.go
  examples/report/main.go
  examples/web/main.go
  graceful/graceful.go
  locker/locker.go
  locker/options.go
  logger/log/log.go
  middlewares/auth/model.go
  middlewares/auth/options.go
  middlewares/auth/user.go
  middlewares/auth/user_test.go
  migrate/helpers.go
  migrate/helpers_test.go
  migrate/migrate.go
  migrate/migrate_test.go
  pprof/pprof.go
  web/bind.go
  web/bind_test.go
  web/errors.go
  web/tracer.go
  web/tracer_test.go
  web/web.go
Labels: docs, examples, features

#115 [GO-000] Bump dependencies
  Gopkg.lock
Labels: vendor

#113 [GO-111] simplest workers v3
  Gopkg.lock
  Gopkg.toml
  examples/workers/main.go
  locker/local/local.go
  locker/local/local_test.go
  workers/constantdelay.go
  workers/constantdelay_test.go
  workers/cron.go
  workers/mockcron_test.go
  workers/mocklogger_test.go
  workers/parser.go
  workers/parser_test.go
  workers/pool.go
  workers/spec.go
  workers/spec_test.go
  workers/worker.go
  workers/workers.go
  workers/workers_test.go
Labels: features

#122 [GO-000] Locker fix
  locker/locker.go
Labels: features
